theme: jekyll-theme-slate
title: ["eBay's TSV utilities toolkit"]
description: ["Command line tools for tabular data files written in the D programming language."]
encoding: utf-8
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  
